{% set name = "easy-thumbnails" %}
{% set version = "2.7" %}
{% set sha256 = "e4e7a0dd4001f56bfd4058428f2c91eafe27d33ef3b8b33ac4e013b159b9ff91" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django >=1.8
    - pillow

test:
  imports:
    - easy_thumbnails

about:
  home: https://github.com/SmileyChris/easy-thumbnails
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Easy thumbnails for Django'
  description: 
    A powerful, yet easy to implement thumbnailing application for Django 1.8+
  doc_url: http://easy-thumbnails.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/SmileyChris/easy-thumbnails

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
