{% set name = "easy-thumbnails" %}
{% set version = "2.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/easy-thumbnails-{{ version }}.tar.gz
  sha256: 7e4e912609fc9b60b3a1fef6557ec15ddf9c4f946267a92e6920dfd4dd765e35

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - django >=2.2
    - pillow

test:
  imports:
    - easy_thumbnails
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/SmileyChris/easy-thumbnails
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Easy thumbnails for Django'
  description: 
    A powerful, yet easy to implement thumbnailing application for Django 1.8+
  doc_url: http://easy-thumbnails.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/SmileyChris/easy-thumbnails

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - rxm7706
