{% set name = "easy-thumbnails" %}
{% set version = "2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7a7e83b48c2b6808d58ce101ddb9ea6eae2c5285e608cc337c2e110a7bb442b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=2.2
    - pillow

test:
  imports:
    - easy_thumbnails
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SmileyChris/easy-thumbnails
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Easy thumbnails for Django'
  description: A powerful, yet easy to implement thumbnailing application for Django 1.8+
  doc_url: http://easy-thumbnails.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/SmileyChris/easy-thumbnails

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - rxm7706
